[workspace]
members = [ "server" ]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
axum = "0.7.4"
shuttle-axum = "0.39.0"
shuttle-runtime = "0.39.0"
tokio = "1.36.0"
tower-http = { version = "0.5.1", features = ["fs"] }
