# This is a copy-template for the real `Secrets.toml` file that is required to make the app work.
# The real `Secrets.toml` is excluded from version control in `.gitignore`.
GITHUB_APP_CLIENT_SECRET = '0123456789abcdef0123456789abcdef'
